/* pcl_config.h. Generated by CMake for PCL. */

/* PCL version string */
#define PCL_VERSION "1.4.0"

/* #undef HAVE_TBB */

/* #undef HAVE_OPENNI */

/* #undef HAVE_QHULL */

/* #undef HAVE_QHULL_2011 */

/* #undef HAVE_CUDA */

#ifdef DISABLE_OPENNI
#undef HAVE_OPENNI
#endif

#ifdef DISABLE_QHULL
#undef HAVE_QHULL
#endif

