CONFIG_ITEM(float, TIME_BEFORE_SPLIT, 3)
CONFIG_ITEM(float, TIME_TOTAL, 180) 
CONFIG_ITEM(float, TIME_SPLITTING_PAUSE, 4)
CONFIG_ITEM(float, TIME_TURN_INVISIBLE, 2)
CONFIG_ITEM(int, MIN_BLOB_SIZE, 10)
CONFIG_ITEM(int, N_SPLITS, 20)
CONFIG_ITEM(int, APP_WIDTH, 800)
CONFIG_ITEM(int, APP_HEIGHT, 600)
CONFIG_ITEM(float, BLOB_SCALE, 0.7f)
CONFIG_ITEM(float, SEC_PER_FRAME_1, 1)
CONFIG_ITEM(float, SEC_PER_FRAME_2, 4)
CONFIG_ITEM(std::string, weibo_usr, "vinjn@sina.com")
CONFIG_ITEM(std::string, weibo_pwd, "p@ssword")
CONFIG_ITEM(std::string, WEIBO_0, "#Body Theatre# is a interaction work based on #Kinect#, server side uses #KinServer# to track hands and extract contour")
CONFIG_ITEM(std::string, WEIBO_1, "The designer and QA of #Body Theatre# is Melanie and I am the programmer,the framework is #Cinder# and #OpenCV#")
CONFIG_ITEM(std::string, WEIBO_2, "The rule of #Body Theatre# is to use your body shape as building blocks to make another you, which will be posted to weibo later")
CONFIG_ITEM(float, HIT_NEAR_RADIUS, 30)