set(CPACK_PACKAGE_NAME "PCL")
set(CPACK_PACKAGE_VENDOR "PointClouds.org")
set(CPACK_PACKAGE_DESCRIPTION_SUMMARY "Point Cloud Library (PCL)")
set(CPACK_PACKAGE_INSTALL_DIRECTORY "PCL 1.4.0")
set(CPACK_RESOURCE_FILE_LICENSE "f:/__svn_pool/CreativeCoding/_PCL/LICENSE.txt")
set(CPACK_RESOURCE_FILE_README "f:/__svn_pool/CreativeCoding/_PCL/AUTHORS.txt")

set(CPACK_COMPONENT_COMMON_DISPLAY_NAME "common")
set(CPACK_COMPONENT_COMMON_DESCRIPTION "Point cloud common library")
set(CPACK_COMPONENT_COMMON_DEPENDS )
set(CPACK_COMPONENT_COMMON_GROUP "PCL")
set(CPACK_COMPONENT_KDTREE_DISPLAY_NAME "kdtree")
set(CPACK_COMPONENT_KDTREE_DESCRIPTION "Point cloud kd-tree library")
set(CPACK_COMPONENT_KDTREE_DEPENDS  common)
set(CPACK_COMPONENT_KDTREE_GROUP "PCL")
set(CPACK_COMPONENT_OCTREE_DISPLAY_NAME "octree")
set(CPACK_COMPONENT_OCTREE_DESCRIPTION "Point cloud octree library")
set(CPACK_COMPONENT_OCTREE_DEPENDS  common)
set(CPACK_COMPONENT_OCTREE_GROUP "PCL")
set(CPACK_COMPONENT_SEARCH_DISPLAY_NAME "search")
set(CPACK_COMPONENT_SEARCH_DESCRIPTION "Point cloud generic search library")
set(CPACK_COMPONENT_SEARCH_DEPENDS  common kdtree octree)
set(CPACK_COMPONENT_SEARCH_GROUP "PCL")
set(CPACK_COMPONENT_RANGE_IMAGE_DISPLAY_NAME "range_image")
set(CPACK_COMPONENT_RANGE_IMAGE_DESCRIPTION "Point cloud range image library")
set(CPACK_COMPONENT_RANGE_IMAGE_DEPENDS  common)
set(CPACK_COMPONENT_RANGE_IMAGE_GROUP "PCL")
set(CPACK_COMPONENT_FEATURES_DISPLAY_NAME "features")
set(CPACK_COMPONENT_FEATURES_DESCRIPTION "Point cloud features library")
set(CPACK_COMPONENT_FEATURES_DEPENDS  common search kdtree octree range_image)
set(CPACK_COMPONENT_FEATURES_GROUP "PCL")
set(CPACK_COMPONENT_SAMPLE_CONSENSUS_DISPLAY_NAME "sample_consensus")
set(CPACK_COMPONENT_SAMPLE_CONSENSUS_DESCRIPTION "Point cloud sample consensus library")
set(CPACK_COMPONENT_SAMPLE_CONSENSUS_DEPENDS  common)
set(CPACK_COMPONENT_SAMPLE_CONSENSUS_GROUP "PCL")
set(CPACK_COMPONENT_FILTERS_DISPLAY_NAME "filters")
set(CPACK_COMPONENT_FILTERS_DESCRIPTION "Point cloud filters library")
set(CPACK_COMPONENT_FILTERS_DEPENDS  common sample_consensus search kdtree octree)
set(CPACK_COMPONENT_FILTERS_GROUP "PCL")
set(CPACK_COMPONENT_IO_DISPLAY_NAME "io")
set(CPACK_COMPONENT_IO_DESCRIPTION "Point cloud IO library")
set(CPACK_COMPONENT_IO_DEPENDS  common octree)
set(CPACK_COMPONENT_IO_GROUP "PCL")
set(CPACK_COMPONENT_KEYPOINTS_DISPLAY_NAME "keypoints")
set(CPACK_COMPONENT_KEYPOINTS_DESCRIPTION "Point cloud keypoints library")
set(CPACK_COMPONENT_KEYPOINTS_DEPENDS  common search kdtree octree range_image features filters)
set(CPACK_COMPONENT_KEYPOINTS_GROUP "PCL")
set(CPACK_COMPONENT_REGISTRATION_DISPLAY_NAME "registration")
set(CPACK_COMPONENT_REGISTRATION_DESCRIPTION "Point cloud registration library")
set(CPACK_COMPONENT_REGISTRATION_DEPENDS  common kdtree sample_consensus features)
set(CPACK_COMPONENT_REGISTRATION_GROUP "PCL")
set(CPACK_COMPONENT_SEGMENTATION_DISPLAY_NAME "segmentation")
set(CPACK_COMPONENT_SEGMENTATION_DESCRIPTION "Point cloud segmentation library")
set(CPACK_COMPONENT_SEGMENTATION_DEPENDS  common search sample_consensus kdtree octree)
set(CPACK_COMPONENT_SEGMENTATION_GROUP "PCL")
set(CPACK_COMPONENT_SURFACE_DISPLAY_NAME "surface")
set(CPACK_COMPONENT_SURFACE_DESCRIPTION "Point cloud surface library")
set(CPACK_COMPONENT_SURFACE_DEPENDS  common search kdtree octree)
set(CPACK_COMPONENT_SURFACE_GROUP "PCL")

set(CPACK_COMPONENT_PCLCONFIG_GROUP "PCL")

set(CPACK_COMPONENT_PCLCONFIG_DISPLAY_NAME "PCLConfig")

set(CPACK_COMPONENT_PCLCONFIG_DESCRIPTION "Helper cmake configuration scripts used by find_package(PCL)")

set(CPACK_COMPONENTS_ALL common kdtree octree search range_image features sample_consensus filters io keypoints registration segmentation surface pclconfig)


IF ((WIN32 OR UNIX) AND (CPACK_GENERATOR STREQUAL "NSIS"))
    set(CPACK_NSIS_DISPLAY_NAME "PCL-1.4.0")
    set(CPACK_NSIS_MUI_ICON "f:/__svn_pool/CreativeCoding/_PCL/cmake/images/pcl.ico")
    set(CPACK_NSIS_MUI_UNIICON "f:/__svn_pool/CreativeCoding/_PCL/cmake/images/pcl.ico")
    set(CPACK_NSIS_HELP_LINK "http:\\\\\\\\www.pointclouds.org")
    set(CPACK_NSIS_URL_INFO_ABOUT "http:\\\\\\\\www.pointclouds.org")
    set(CPACK_NSIS_MODIFY_PATH ON)
    set(CPACK_PACKAGE_EXECUTABLES )
    set(CPACK_NSIS_MENU_LINKS 
            "share/doc/pcl/tutorials/html/index.html" "Tutorials"
            "share/doc/pcl/tutorials/html/sources" "Tutorials sources"
            "share/doc/pcl/html/pcl-1.4.chm" "Documentation"
            "http://www.pointclouds.org" "PCL Website")
    #set(CPACK_NSIS_MENU_LINKS "share/doc/PCL/user_guide.pdf" "User's guide")
    #set(CPACK_NSIS_MENU_LINKS "share/doc/PCL/developer_guide.pdf" "Developer's guide")
    if(WIN32 AND NOT UNIX)
      # There is a bug in NSI that does not handle full unix paths properly. Make
      # sure there is at least one set of four (4) backlasshes.
      set(CPACK_PACKAGE_ICON "f:/__svn_pool/CreativeCoding/_PCL/cmake/images\\\\pcl_horz_large_pos.bmp")
    else(WIN32 AND NOT UNIX)
      set(CPACK_PACKAGE_ICON "f:/__svn_pool/CreativeCoding/_PCL/cmake/images/pcl_horz_large_pos.bmp")
    endif(WIN32 AND NOT UNIX)
ENDIF ()

IF (UNIX AND ((CPACK_GENERATOR STREQUAL "DEB") OR (CPACK_GENERATOR STREQUAL "RPM")))
    # define stuff for the DEB/RPM packages
    set(CPACK_PACKAGE_CONTACT "pcl-developers@pointclouds.org")
ENDIF ()

IF (UNIX AND (CPACK_GENERATOR STREQUAL "DEB"))
  SET(CPACK_DEBIAN_PACKAGE_SHLIBDEPS ON)
ENDIF ()

IF (APPLE AND (CPACK_GENERATOR STREQUAL "PackageMaker"))
    # define stuff for the PackageMaker packages
    set(CPACK_OSX_PACKAGE_VERSION 10.5)
    set(CPACK_PACKAGE_CONTACT "pcl-developers@pointclouds.org")
    set(CPACK_SET_DESTDIR ON)
    set(CPACK_PACKAGING_INSTALL_PREFIX /opt/local)
ENDIF ()
